const comic = [
  {
    id: "1",
    name: "Tôi Thăng Cấp Một Mình Phần 2",
    chapter: "51",
    view: "25.993.982",
    urlImg: "assests/image/anh1.jpg",
  },
  {
    id: "2",
    name: "Vua thăng cấp",
    chapter: "93",
    view: "14.946.089",
    urlImg: "assests/image/anh2.jpg",
  },
  {
    id: "3",
    name: "Luân Hồi Ác Nhân",
    chapter: "75",
    view: "8.635.015",
    urlImg: "assests/image/anh3.jpg",
  },
  {
    id: "4",
    name: "Cậu Bé Của Thần Chết",
    chapter: "111",
    view: "8.260.466",
    urlImg: "assests/image/anh4.jpg",
  },
  {
    id: "5",
    name: "FFF-Class Trashero",
    chapter: "92",
    view: "9.406.348",
    urlImg: "assests/image/anh5.jpg",
  },
  {
    id: "6",
    name: "Bạn Học Của Tôi Là Lính Đánh Thuê",
    chapter: "44",
    view: "7.778.143",
    urlImg: "assests/image/anh6.jpg",
  },
  {
    id: "7",
    name: "Tôi là người chơi leo tháp một mình",
    chapter: "70",
    view: "7.342.164",
    urlImg: "assests/image/anh7.jpg",
  },
  {
    id: "8",
    name: "Bắc Kiếm Giang Hồ",
    chapter: "94",
    view: "7.097.067",
    urlImg: "assests/image/anh8.jpg",
  },
  {
    id: "9",
    name: "Kẻ Bị Ruồng Bỏ",
    chapter: "69.7",
    view: "5.721.464",
    urlImg: "assests/image/anh9.jpg",
  },
  {
    id: "10",
    name: "Biên Niên Sử Của Thiên Quỷ",
    chapter: "151",
    view: "5.568.861",
    urlImg: "assests/image/anh10.jpg",
  },
  {
    id: "11",
    name: "Sự ra đời của một anh hùng",
    chapter: "52",
    view: "5.266.748",
    urlImg: "assests/image/anh11.jpg",
  },
  {
    id: "12",
    name: "Ngã lão ma thần",
    chapter: "65",
    view: "5.196.518",
    urlImg: "assests/image/anh12.jpg",
  },
  {
    id: "13",
    name: "Học Nhóm",
    chapter: "85",
    view: "4.342.904",
    urlImg: "assests/image/anh13.jpg",
  },
  {
    id: "14",
    name: "Phá Bỏ Giới Hạn",
    chapter: "42",
    view: " 3.291.743",
    urlImg: "assests/image/anh14.jpg",
  },
  {
    id: "15",
    name: "Bá Chủ Học Đường SS3",
    chapter: "33",
    view: "2.822.961",
    urlImg: "assests/image/anh15.jpg",
  },
  {
    id: "16",
    name: "Tam Tuyệt Tại Dị Giới",
    chapter: "102",
    view: "2.798.665",
    urlImg: "assests/image/anh16.jpg",
  },
  {
    id: "17",
    name: "Hồi ức Của Chiến Thần",
    chapter: "54",
    view: "2.366.366",
    urlImg: "assests/image/anh17.jpg",
  },
  {
    id: "18",
    name: "Người máy hủy diệt",
    chapter: "147",
    view: "2.344.657",
    urlImg: "assests/image/anh18.jpg",
  },
  {
    id: "19",
    name: "Sự Trở Lại Của Pháp Sư Cấp 8",
    chapter: "25",
    view: "2.064.671",
    urlImg: "assests/image/anh19.jpg",
  },
  {
    id: "20",
    name: "Võ Đang Kỳ Hiệp",
    chapter: "40.2",
    view: "1.898.139",
    urlImg: "assests/image/anh20.jpg",
  },
];

export default comic;
